apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- issuer/argo-cd-issuer.yaml
- certificate/argo-cd-certificate.yaml
- ingress/argocd-ingress.yaml
- base/sync-project.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/ha/install.yaml
- https://github.com/cert-manager/cert-manager/releases/download/v1.14.2/cert-manager.yaml