apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - argocd-server-service.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  - https://github.com/cert-manager/cert-manager/releases/download/v1.15.3/cert-manager.yaml